// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYyBo-OHfSJU3Q9FvIu1H9sni7pTkaGU',
    appId: '1:44063603441:android:1e0b933b2c786cef5fc750',
    messagingSenderId: '44063603441',
    projectId: 'amira-store-6bb3d',
    storageBucket: 'amira-store-6bb3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZ5ORcwc9gu1v4DxoVJSasIR7qlsFLTY',
    appId: '1:44063603441:ios:4f716820720535455fc750',
    messagingSenderId: '44063603441',
    projectId: 'amira-store-6bb3d',
    storageBucket: 'amira-store-6bb3d.firebasestorage.app',
    androidClientId:
        '44063603441-bea6jn0g1r39truv8gma3e5up5bhgpgg.apps.googleusercontent.com',
    iosClientId:
        '44063603441-vfb4tm05okoi3angdkrg3qsrscj8ugnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.amiraStore',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJ2QYULYJw-QbLqEfYOPixcHo7U57dS0',
    appId: '1:44063603441:web:57eab0ea21e336db5fc750',
    messagingSenderId: '44063603441',
    projectId: 'amira-store-6bb3d',
    authDomain: 'amira-store-6bb3d.firebaseapp.com',
    storageBucket: 'amira-store-6bb3d.firebasestorage.app',
  );
}
